name: Weighted Assign Action123123
description: AA GitHub app that writes a message to a closed PR
author: Smrinov Aleksandr
branding:
  icon: move
  color: green
inputs:
  repo-token:
    description: Github token secret
    required: true
  config:
    description: "Path to config file"
    default: .github/reviewers.txt
runs:
  using: node10
  main: ./dist/index.js